/* javascriptcore-gtk.vapi generated by valac 0.40.4, do not modify. */

[CCode (cheader_filename = "web-extension.h", cname = "G_MODULE_EXPORT webkit_web_extension_initialize_with_user_data", has_target = false)]
public static void webkit_web_extension_initialize_with_user_data (WebKit.WebExtension extension, GLib.Variant user_data);
